targets:
  $default:
    builders:
      static_aligator_ir|relocation_builder:
        enabled: true
      static_aligator_ir|cleanup_builder:
        enabled: true
builders:
  markdown_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .md:
        - .html
    auto_apply: root_package
    required_inputs:
      - .md
    applies_builders:
      - template_builder
  sitemap_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factories:
      - sitemapBuilder
    build_extensions:
        $package$:
          - web/sitemap.xml
          - web/robot.txt
    auto_apply: root_package
    applies_builders:
      - markdown_builder
  template_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factories:
      - templateBuilder
    build_extensions:
      .mustache:
        - .mustacheslug
    auto_apply: root_package
post_process_builders:
  relocation_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factory: relocationBuilder
    input_extensions:
      - .html
  cleanup_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factory: cleanupBuilder
    input_extensions:
      - .md
      - .mustache
      - .mustacheslug