builders:
  markdown_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .md:
        - .html
    auto_apply: root_package
    required_inputs:
      - .md
  sitemap_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factories:
      - sitemapBuilder
    build_extensions:
        $package$:
          - web/sitemap.xml
    auto_apply: root_package
    applies_builders:
      - markdown_builder
  minified_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factories:
      - minifiedBuilder
    build_extensions:
      .css:
        - .min.css
    auto_apply: root_package
    applies_builders:
      - sass_builder
post_process_builders:
  cleanup_builder:
    import: "package:static_aligator_ir/builders.dart"
    builder_factory: cleanupBuilder
    input_extensions:
      - .md
      - .mustache
