name: static_aligator_ir
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.aligator.ir

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: any

  yaml: ^2.2.1
  mustache: ^1.1.1
  markdown: ^2.1.3
  sass: any
  http: any

dev_dependencies:
  build_runner: ^1.7.3
  build_web_compilers: ^2.9.0
  pedantic: ^1.8.0
  sass_builder: ^2.1.2