name: static_aligator_ir
description: An absolute bare-bones web app.
version: 1.0.0
homepage: https://www.aligator.ir

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: any

  build: any
  build_config: 0.4.2
  glob: ^1.2.0
  path: ^1.7.0

  csv: ^4.0.3
  xml:
  yaml: ^2.2.1
  mustache: ^1.1.1
  markdown: ^2.1.4
  sass: any


dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0
  sass_builder: ^2.1.3
