name: os_aligator_ir
description: An absolute bare-bones web app.
version: 1.0.0
homepage: https://os.aligator.ir

environment:
  sdk: '>=2.7.0 <2.10.5'

dependencies:
  os_cpu_schedulers:
    path: os_cpu_schedulers
  os_memory_allocators:
    path: os_memory_allocators

  angular: 6.0.0
  angular_components: ^1.0.2
  angular_router: ^2.0.0
  angular_forms: ^3.0.0
  darq: ^0.4.0+1

  build: any
  build_config: 0.4.2
  meta: ^1.2.4
  glob: ^1.2.0
  path: ^1.7.0
  sass: 1.26.10


dev_dependencies:
  test:
  build_runner: ^1.10.0
  #build_resolvers: ^1.3.11
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.2
  sass_builder: ^2.1.3
  angular_test: ^3.0.0
  build_test: ^0.10.8
