name: static_aligator_ir
description: An absolute bare-bones web app.
version: 1.0.0
homepage: https://www.aligator.ir

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: ^0.14.0-alpha+1
  angular_router: ^2.0.0-alpha+22

  http: 0.12.2
  fanoos_http:
  abstarct_date: ^0.0.6

  build: any
  build_config: 0.4.2
  meta: ^1.2.2
  glob: ^1.2.0
  path: ^1.7.0

  csv: ^4.0.3
  xml: ^4.4.1
  yaml: ^2.2.1
  mustache: ^1.1.1
  markdown: ^2.1.8
  sass: 1.26.10


dev_dependencies:
  build_runner: ^1.7.0
  #build_resolvers: ^1.3.11
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.1
  sass_builder: ^2.1.3
  angular_test: ^2.3.1
  build_test: ^0.10.8
