name: os_cpu_schedulers
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  test:
  pedantic: ^1.9.0
