name: os_memory_allocators
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  darq:
  pretty_json: ^1.1.0

dev_dependencies:
  test:
  pedantic: ^1.9.0
